---
title: "iea-auto monthly+"
author: "Ben Best"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F)
```

```{r libs}
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  clockify, dplyr, DT, glue, lubridate, readr)

# CLOCKIFY_API_KEY = Sys.getenv("CLOCKIFY_API_KEY")
CLOCKIFY_API_KEY = readLines("~/My Drive (ben@ecoquants.com)/private/clockify-api-key_ben@ecoquants.com.txt")
set_api_key(CLOCKIFY_API_KEY)

# library(logger)
# log_threshold(DEBUG)
```

```{r times}
project_name <- "iea-auto"
  
t_now        <- Sys.time() 
t_beg_thiswk <- as.Date(t_now) - days(7)
t_beg_thismo <- date(glue("{year(t_now)}-{month(t_now)}-01"))
t_end_lastmo <- date(glue("{year(t_now)}-{month(t_now)}-01")) - days(1)
t_beg_lastmo <- date(glue("{year(t_end_lastmo)}-{month(t_end_lastmo)}-01")) - days(1)

d_times <- time_entries(
  start = format(t_beg_lastmo, '%Y-%m-%d 00:00:00'),
  end   = format(t_now, '%Y-%m-%d %H:%M:%S'),
  concise = F) %>% 
  left_join(
    projects() %>% 
      select(project_id, project_name), 
    by = "project_id") %>% 
  mutate(
    date_start = as.Date(time_start))

d_proj <- d_times %>% 
  filter(project_name == !!project_name) %>% 
  rename(date = date_start) %>% 
  group_by(date) %>% 
  summarize(
    hrs          = round(sum(duration)/60, 1),
    description  = paste(description, collapse = " ; ")) %>% 
  mutate(
    day = format(date, "%a")) %>% 
  select(day, date, hrs, description) %>% 
  arrange(desc(date))

timetable <- function(d){
  d %>% 
    select(-day) %>% 
    datatable(
      rownames = F,
      extensions = 'Buttons', options = list(
        dom = 'Bfrtip',
        buttons = c('copy', 'csv', 'excel'))) %>% 
  formatDate("date", "toDateString")
}
```

## This Week: `r format(t_beg_thiswk, '%a %m/%d')` to `r format(t_now, '%a %m/%d')`

```{r}
d_thiswk <- d_proj %>% 
  filter(
    date <= t_now,
    date >= t_beg_thiswk)
write_csv(d_thiswk, glue("data/iea-auto_thiswk_{as.Date(t_now)}.csv"))

timetable(d_thiswk)
```

- Hours this week: `r sum(d_thiswk$hrs)`

## This Month: `r format(t_now, '%B %Y-%m')`

```{r}
d_thismo <- d_proj %>% 
  filter(
    date <= t_now,
    date >= t_beg_thismo)
write_csv(d_thismo, glue("data/iea-auto_thismo_{as.Date(t_now)}.csv"))

timetable(d_thismo)
```

- Hours this month: `r sum(d_thismo$hrs)`

## Last Month: `r format(t_end_lastmo, '%B %Y-%m')`

```{r}
d_lastmo <- d_proj %>% 
  filter(
    date <= t_end_lastmo,
    date >= t_beg_lastmo)
write_csv(d_lastmo, glue("data/iea-auto_lastmo_{as.Date(t_now)}.csv"))

timetable(d_lastmo)
```

- Hours lst month: `r sum(d_lastmo$hrs)`


## References

- using: [clockify](https://datawookie.github.io/clockify/) R package, which uses the [Clockify API](https://clockify.me/developers-api#tag-Time-entry)
